#!/usr/bin/env ruby
require 'bunny'

connection = Bunny.new(username: 'tutorial', password: 'impostersyndrome')
connection.start

channel = connection.create_channel
queue = channel.queue('hello')

puts ' [*] Waiting for messages. To exit press CTRL+C'

begin
  queue.subscribe(block: true) do |_delivery_info, _properties, body|
    puts " [x] Received #{body}"
  end
rescue Interrupt => _
  connection.close
end
