#!/usr/bin/env ruby
require 'bunny'
require 'json'

puts "STARTING WITH RABBITMQ_URL '#{ENV['RABBITMQ_URL']}'"
connection = Bunny.new
connection.start

channel = connection.create_channel
exchange = channel.default_exchange

reply_queue = channel.queue('', exclusive: true)
reply_queue.subscribe do |_delivery_info, properties, payload|
  puts "[#{properties.correlation_id}] #{payload}"
end

server_queue = channel.queue('rpc_queue')
begin
  puts "type a cid and complexity: <cid> <complexity>"
  loop do
    print "job> "
    cid, cmp = gets.chomp.split(' ')
    exchange.publish(
      JSON.dump({ complexity: Integer(cmp, 10, exception: false) || 0 }),
      routing_key: 'rpc_queue',
      content_type: 'application/json',
      correlation_id: cid,
      reply_to: reply_queue.name
    )
  end
rescue Interrupt => _
  channel.close
  connection.close
end
